version: '3'

services:
  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=psql://postgres:postgres@db:5432/billing
      - DJANGO_SETTINGS_MODULE=settings
    depends_on:
      - db
  db:
    image: postgres:11.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=billing

volumes:
  postgres_data: