# Generated by Django 3.0.7 on 2020-06-17 20:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import wallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=wallet.models.get_default_name, max_length=36)),
                ('balance', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
            ],
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['name'], name='name_idx'),
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.CheckConstraint(check=models.Q(balance__gte=0), name='non_negative_balance'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_from',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='wallet.Wallet'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to='wallet.Wallet'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet_from'], name='wallet_from_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['wallet_to'], name='wallet_to_idx'),
        ),
    ]
